# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1316Bbz5LvG8aV7P7O1mVPNeZvl0IiiPf
"""

import pandas as pd
data={'Product_Name':['Iron_box','T_shirt','Pan','KeyBoard','Jeans_pants'],
      'category':['Electronics','Clothing','kitchen','Electronics','Clothing'],
      'Price':[1000,700,300,800,1300],
      'Quantity_Sold':[3,4,2,1,5]}

df=pd.DataFrame(data)
pd.pivot_table(df,index=['category'],values=('Price'),aggfunc='mean')

import pandas as pd
data={'Product_Name':['Iron_box','T_shirt','Pan','KeyBoard','Jeans_pants'],
      'category':['Electronics','Clothing','kitchen','Electronics','Clothing'],
      'Price':[1000,700,300,800,1300],
      'Quantity_Sold':[3,4,2,1,5]}

df=pd.DataFrame(data)
pd.pivot_table(df,values=['Quantity_Sold','Price'],aggfunc=['sum','mean'],index='category')

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/mtcars.csv')

plt.hist(df['mpg'],edgecolor='k')
plt.xlabel('Miles per gallon')
plt.ylabel('Frequency distribution')
plt.title('HISTOGRAM')
plt.show()

import matplotlib.pyplot as plt

df=pd.read_csv('/content/mtcars.csv')

plt.scatter(df['wt'],df['mpg'],color='red')
plt.xlabel('Weight of the cars')
plt.ylabel('Miles per gallon')
plt.title('SCATTER PLOT')
plt.show()

import matplotlib.pyplot as plt

df=pd.read_csv('/content/mtcars.csv')
transmission=df['am'].value_counts()
transmission.plot(kind='bar')
plt.xlabel('frequency Distibution')
plt.ylabel('Trasmission of cars')
plt.title('BAR PLOT')
plt.show()

import matplotlib.pyplot as plt

df=pd.read_csv('/content/mtcars.csv')
plt.boxplot(df['mpg'])
plt.xlabel('Miles per gallon')
plt.ylabel('interpert the five number summaries')
plt.title('Box Plot')
plt.show()